import options

class_dicts = {
    '충북대학교':
        {
            'main_url': 'https://www.cbnu.ac.kr/www/selectBbsNttList.do?key=813&bbsNo=8&pageUnit=10&searchCnd=all&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbsNttForm fieldset div.table-responsive table tr',
            'artMainUrl': 'https://www.cbnu.ac.kr/www/',
            'artUrlSubTag': 'td.p-subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1) > span',
            'art_date_tag': '',
            'art_title_tag': '#contents > div > div > div.subjectbox',
            'page_date_tag': 'td:nth-child(6)',
            'page_title_tag': 'td.p-subject > a'
        },
    '기숙사':
        {
            'main_url': 'https://dorm.chungbuk.ac.kr/home/sub.php?menukey=20039&mod=&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contentBody form div.containerIn table tr',
            'artMainUrl': 'https://dorm.chungbuk.ac.kr/home/',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.num',
            'art_date_tag': '#contentBody > div.containerIn > table.board_insert > tbody > tr:nth-child(2) > td:nth-child(4)',
            'art_title_tag': '#contentBody > div.containerIn > table.board_insert > tbody > tr:nth-child(1) > th',
            'page_date_tag': 'td.date',
            'page_title_tag': 'td.title'},

    # 전자정보
    '전자공학부':
        {
            'main_url': 'https://elec.chungbuk.ac.kr/bbs/bbs.php?db=notice&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#subContent table tr',
            'artMainUrl': 'https://elec.chungbuk.ac.kr/',
            'artUrlSubTag': 'nobr > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#body_line',
            'art_date_tag': '#view_bg > span',
            'art_title_tag': '#subContent table tr td nobr',
            'page_date_tag': '#body_line:nth-child(7)',
            'page_title_tag': '#body_line > nobr > a > span'},

    '전기공학부':
        {
            'main_url': 'https://koamma.chungbuk.ac.kr/bbs/bbs.php?db=notice&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#subContent > div.section > table:nth-child(6) tr',
            'artMainUrl': 'https://koamma.chungbuk.ac.kr/',
            'artUrlSubTag': '#body_line > nobr > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#body_line',
            'art_date_tag': '#view_bg > span',
            'art_title_tag': '#subContent table tr td nobr',
            'page_date_tag': '#body_line:nth-child(7)',
            'page_title_tag': '#body_line > nobr > a', },

    '정보통신공학부':
        {
            'main_url': 'https://inform.chungbuk.ac.kr/bbs/bbs.php?db=notice&&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#content1 div.section.clear table:nth-child(6) tr',
            'artMainUrl': 'https://inform.chungbuk.ac.kr/',
            'artUrlSubTag': 'nobr > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#body_line',
            'art_date_tag': '#view_bg > span',
            'art_title_tag': '#content1 div.section.clear table:nth-child(6) tr:nth-child(3) td nobr',
            'page_date_tag': '#body_line:nth-child(7)',
            'page_title_tag': '#body_line > nobr'},

    '컴퓨터공학과':
        {
            'main_url': 'https://computer.chungbuk.ac.kr/bbs/bbs.php?db=notice&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#content table tr',
            'artMainUrl': 'https://computer.chungbuk.ac.kr/',
            'artUrlSubTag': 'nobr > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#body_line',
            'art_date_tag': '#view_bg > span',
            'art_title_tag': '#content table tr td nobr',
            'page_date_tag': '#body_line:nth-child(7)',
            'page_title_tag': '#body_line > nobr'},

    '지능로봇공학과':
        {
            'main_url': 'https://airobot.chungbuk.ac.kr/index.php?mid=airbot_0702&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bd_200_0 div.bd_lst_wrp table tr',
            'artMainUrl': 'https://airobot.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.no',
            'art_date_tag': 'div.bd > div > div > div > div.ngeb > div > span',
            'art_title_tag': '#bd_200_18739 > div.rd.rd_nav_style2.clear > div.rd_hd.clear > div.board.clear > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title'},

    '소프트웨어학부':
        {
            'main_url': 'https://software.cbnu.ac.kr/index.php?mid=sub0401&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bd_197_0 div.bd_lst_wrp table tr',
            'artMainUrl': 'https://software.cbnu.ac.kr/',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.no',
            'art_date_tag': 'div.bd > div > div > div > div.ngeb > div > span',
            'art_title_tag': '#bd_197_15132 > div.rd.rd_nav_style2.clear > div.rd_hd.clear > div.board.clear > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title'},

    # 인문
    '국어국문학과':
        {
            'main_url': 'https://humanum.chungbuk.ac.kr/korean/selectBbsNttList.do?key=562&bbsNo=172&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contents table tr',
            'artMainUrl': 'https://humanum.chungbuk.ac.kr/korean/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#contents > table tr > td.first',
            'art_date_tag': '#contents > div.bbs_info.clearfix > div.bbs_left.bbs_count > span:nth-child(1) > strong',
            'art_title_tag': '#contents > table tr.subject > td',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '중어중문학과':
        {
            'main_url': 'https://humanum.chungbuk.ac.kr/chinese/selectBbsNttList.do?key=293&bbsNo=73&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contents table tr',
            'artMainUrl': 'https://humanum.chungbuk.ac.kr/chinese/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#contents > table tr > td.first',
            'art_date_tag': '#contents > div.bbs_info.clearfix > div.bbs_left.bbs_count > span:nth-child(1) > strong',
            'art_title_tag': '#contents > table tr.subject > td',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '영어영문학과':
        {
            'main_url': 'https://humanum.chungbuk.ac.kr/ecbnu/selectBbsNttList.do?key=621&bbsNo=180&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contents table tr',
            'artMainUrl': 'https://humanum.chungbuk.ac.kr/ecbnu/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#contents > table tr > td.first',
            'art_date_tag': '#contents > div.bbs_info.clearfix > div.bbs_left.bbs_count > span:nth-child(1) > strong',
            'art_title_tag': '#contents > table tr.subject > td',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '프랑스언어문화학과':
        {
            'main_url': 'https://humanum.chungbuk.ac.kr/french/selectBbsNttList.do?key=771&bbsNo=81&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contents table tr',
            'artMainUrl': 'https://humanum.chungbuk.ac.kr/french/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#contents > table tr > td.first',
            'art_date_tag': '#contents > div.bbs_info.clearfix > div.bbs_left.bbs_count > span:nth-child(1) > strong',
            'art_title_tag': '#contents > table tr.subject > td',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '러시아언어문화학과':
        {
            'main_url': 'https://humanum.chungbuk.ac.kr/russian/selectBbsNttList.do?key=339&bbsNo=93&pageIndex=',

            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contents table tr',
            'artMainUrl': 'https://humanum.chungbuk.ac.kr/russian/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#contents > table tr > td.first',
            'art_date_tag': '#contents > div.bbs_info.clearfix > div.bbs_left.bbs_count > span:nth-child(1) > strong',
            'art_title_tag': '#contents > table tr.subject > td',
            'page_date_tag': '',  # 시간정보 없음
            'page_title_tag': 'td.subject > a'},

    '독일언어문화학과':
        {
            'main_url': 'https://humanum.chungbuk.ac.kr/german/selectBbsNttList.do?key=506&bbsNo=149&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contents table tr',
            'artMainUrl': 'https://humanum.chungbuk.ac.kr/german/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#contents > table tr > td.first',
            'art_date_tag': '#contents > div.bbs_info.clearfix > div.bbs_left.bbs_count > span:nth-child(1) > strong',
            'art_title_tag': '#contents > table tr.subject > td',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '철학과':
        {
            'main_url': 'https://humanum.chungbuk.ac.kr/philosophy/selectBbsNttList.do?key=366&bbsNo=99&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contents table tr',
            'artMainUrl': 'https://humanum.chungbuk.ac.kr/philosophy/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#contents > table tr > td.first',
            'art_date_tag': '#contents > div.bbs_info.clearfix > div.bbs_left.bbs_count > span:nth-child(1) > strong',
            'art_title_tag': '#contents > table tr.subject > td',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '사학과':
        {
            'main_url': 'https://humanum.chungbuk.ac.kr/cbnuhistory/selectBbsNttList.do?key=388&bbsNo=98&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contents table tr',
            'artMainUrl': 'https://humanum.chungbuk.ac.kr/cbnuhistory/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#contents > table tr > td.first',
            'art_date_tag': '#contents > div.bbs_info.clearfix > div.bbs_left.bbs_count > span:nth-child(1) > strong',
            'art_title_tag': '#contents > table tr.subject > td',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '고고미술사학과':
        {
            'main_url': 'https://humanum.chungbuk.ac.kr/gomisa/selectBbsNttList.do?key=683&bbsNo=218&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contents table tr',
            'artMainUrl': 'https://humanum.chungbuk.ac.kr/gomisa/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#contents > table tr > td.first',
            'art_date_tag': '#contents > div.bbs_info.clearfix > div.bbs_left.bbs_count > span:nth-child(1) > strong',
            'art_title_tag': '#contents > table tr.subject > td',
            'page_date_tag': 'td.last',
            'page_title_tag': 'td.subject > a'},

    # 사회과학대학
    '사회학과':
        {  # TODO 월-일
            'main_url': 'https://sociology.chungbuk.ac.kr/board/department_notice?&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#fboardlist table tr',
            'artMainUrl': 'https://sociology.chungbuk.ac.kr/',
            'artUrlSubTag': 'td > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'body > div > div.container > div > div.fl_grow > div:nth-child(3) > div > div:nth-child(2)',
            'art_title_tag': 'body > div > div.container > div > div.fl_grow > div:nth-child(3) > div > div:nth-child(1)',
            'page_date_tag': 'td:nth-child(4)',
            'page_title_tag': 'td > a:last-child'},

    '심리학과':
        {  # TODO 월-일
            'main_url': 'https://psychology.chungbuk.ac.kr/board/department_notice?&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#fboardlist table tr',
            'artMainUrl': 'https://sociology.chungbuk.ac.kr/',
            'artUrlSubTag': 'td > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'body > div > div.container > div > div.fl_grow > div:nth-child(3) > div > div:nth-child(2)',
            'art_title_tag': 'body > div > div.container > div > div.fl_grow > div:nth-child(3) > div > div:nth-child(1)',
            'page_date_tag': 'td:nth-child(4)',
            'page_title_tag': 'td > a:last-child'},

    '행정학과':
        {  # TODO 날짜 로직에러 수정하기, 월 일만나와있음
            'main_url': 'https://public.chungbuk.ac.kr/board/department_notice?&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#fboardlist table tr',
            'artMainUrl': 'https://public.chungbuk.ac.kr/',
            'artUrlSubTag': 'td > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'body > div > div.container > div > div.fl_grow > div:nth-child(3) > div > div:nth-child(2)',
            'art_title_tag': 'body > div > div.container > div > div.fl_grow > div:nth-child(3) > div > div:nth-child(1)',
            'page_date_tag': 'td:nth-child(4)',
            'page_title_tag': 'td > a:last-child'},

    '정치외교학과':
        {  # TODO 월-일
            'main_url': 'https://politics.chungbuk.ac.kr/board/department_notice?&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#fboardlist table tr',
            'artMainUrl': 'https://politics.chungbuk.ac.kr/',
            'artUrlSubTag': 'td > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'body > div > div.container > div > div.fl_grow > div:nth-child(3) > div > div:nth-child(2)',
            'art_title_tag': 'body > div > div.container > div > div.fl_grow > div:nth-child(3) > div > div:nth-child(1)',
            'page_date_tag': 'td:nth-child(4)',
            'page_title_tag': 'td > a:last-child'},

    '경제학과':
        {  # TODO 월-일
            'main_url': 'https://econ.chungbuk.ac.kr/board/department_notice?&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#fboardlist table tr',
            'artMainUrl': 'https://econ.chungbuk.ac.kr/',
            'artUrlSubTag': 'td > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'body > div > div.container > div > div.fl_grow > div:nth-child(3) > div > div:nth-child(2)',
            'art_title_tag': 'body > div > div.container > div > div.fl_grow > div:nth-child(3) > div > div:nth-child(1)',
            'page_date_tag': 'td:nth-child(4)',
            'page_title_tag': 'td > a:last-child'},

    # 공대
    '토목공학부':
        {
            'main_url': 'https://civil.chungbuk.ac.kr/index.php?mid=civil_sub0301&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bd_300_0 > div.bd_lst_wrp > table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#bd_300_0 div.bd_lst_wrp table tr td.no',
            'art_date_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
            'art_title_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a'},

    '화학공학과':
        {
            'main_url': 'https://cheme.cbnu.ac.kr/index.php?mid=cheme_sub04&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': 'div.bd_lst_wrp > table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'div.bd_lst_wrp table tr td.no',
            'art_date_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
            'art_title_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a'},

    '기계공학부':
        {
            'main_url': 'https://me.chungbuk.ac.kr/index.php?mid=me5_1&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bd_172_0 div.bd_lst_wrp table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.no',
            'art_date_tag': '#bd_172_6299 > div.rd.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
            'art_title_tag': '#bd_172_6299 > div.rd.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a'},

    '신소재공학과':
        {
            'main_url': 'https://material.cbnu.ac.kr/index.php?mid=material5_1_1&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bd_172_0 div.bd_lst_wrp table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.no',
            'art_date_tag': '#bd_172_6299 > div.rd.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
            'art_title_tag': '#bd_172_6299 > div.rd.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a'},

    '건축공학과':
        {
            'main_url': 'https://cbnuae.cbnu.ac.kr/index.php?mid=cbnuae_sub05&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': 'div.bd_lst_wrp > table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'div.bd_lst_wrp table tr td.no',
            'art_date_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
            'art_title_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a'},

    '안전공학과':
        {
            'main_url': 'https://safety.cbnu.ac.kr/index.php?mid=safety_sub04&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': 'div.bd_lst_wrp > table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'div.bd_lst_wrp table tr td.no',
            'art_date_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
            'art_title_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a'},

    '환경공학과':
        {
            'main_url': 'https://env.cbnu.ac.kr/index.php?mid=env_sub05&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': 'div.bd_lst_wrp > table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'div.bd_lst_wrp table tr td.no',
            'art_date_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
            'art_title_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a'},

    '공업화학과':
        {  # TODO 체크
            'main_url': 'https://cbec.cbnu.ac.kr/index.php?mid=cbec5_1_1&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bd_172_0 div.bd_lst_wrp table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.no',
            'art_date_tag': '#bd_172_6299 > div.rd.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
            'art_title_tag': '#bd_172_6299 > div.rd.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a'},

    '도시공학과':
        {
            'main_url': 'https://urban.cbnu.ac.kr/index.php?mid=urban_sub05&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': 'div.bd_lst_wrp > table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'div.bd_lst_wrp table tr td.no',
            'art_date_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
            'art_title_tag': 'div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a'},

    '건축학과_뉴스':
        {  # 뉴스
            'main_url': 'https://cbnuarchi.cbnu.ac.kr/bbs/board.php?bo_table=news&sca=%EB%89%B4%EC%8A%A4&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bo_list > div > ul:nth-child(2) > li',
            'artMainUrl': '',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'div > a > span:nth-child(1)',
            'art_date_tag': '#bo_v_info > span:nth-child(7)',
            'art_title_tag': '#bo_v_title > span.bo_v_tit',
            'page_date_tag': ' div > a > span.bo_date',
            'page_title_tag': 'div > a > span:nth-child(2)'},
    '건축학과_공모전':
        {  # 공모전
            'main_url': 'https://cbnuarchi.cbnu.ac.kr/bbs/board.php?bo_table=news&sca=%EA%B3%B5%EB%AA%A8%EC%A0%84+%EB%B0%8F+%EC%B1%84%EC%9A%A9%EC%A0%95%EB%B3%B4&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bo_list > div > ul:nth-child(2) > li',
            'artMainUrl': '',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'div > a > span:nth-child(1)',
            'art_date_tag': '#bo_v_info > span:nth-child(7)',
            'art_title_tag': '#bo_v_title > span.bo_v_tit',
            'page_date_tag': ' div > a > span.bo_date',
            'page_title_tag': 'div > a > span:nth-child(2)'},

    # 자연과학
    '수학과':
        {
            'main_url': 'https://math.chungbuk.ac.kr/?pg_idx=145&bidx=1&id=101&cate=&pidx=0&str=&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div table tr',
            'artMainUrl': 'https://math.chungbuk.ac.kr/',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head> div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},

    '정보통계학과':
        {
            'main_url': 'https://stat.chungbuk.ac.kr/master.php?pg_idx=145&page',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div table tr',
            'artMainUrl': 'https://stat.chungbuk.ac.kr/',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},

    '물리학과':
        {
            'main_url': 'https://physics.chungbuk.ac.kr/master.php?pg_idx=145&page',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div table tr',
            'artMainUrl': 'https://physics.chungbuk.ac.kr/',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},

    '화학과':
        {
            'main_url': 'https://chem.chungbuk.ac.kr/master.php?pg_idx=145&page',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div table tr',
            'artMainUrl': 'https://chem.chungbuk.ac.kr/',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},

    '생물학과':
        {
            'main_url': 'https://biology.chungbuk.ac.kr/master.php?pg_idx=145&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div table tr',
            'artMainUrl': 'https://biology.chungbuk.ac.kr/',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},

    '미생물학과':
        {
            'main_url': 'https://microbio.chungbuk.ac.kr/master.php?pg_idx=145&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div table tr',
            'artMainUrl': 'https://microbio.chungbuk.ac.kr/',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},

    '생화학과':
        {
            'main_url': 'https://biochem.chungbuk.ac.kr/master.php?pg_idx=145&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div table tr',
            'artMainUrl': 'https://biochem.chungbuk.ac.kr/',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},

    '천문우주학과_학부':
        {
            'main_url': 'https://ast.chungbuk.ac.kr/master.php?pg_idx=145&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div table tr',
            'artMainUrl': 'https://ast.chungbuk.ac.kr/',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},
    '천문우주학과_학과':
        {
            'main_url': 'https://ast.chungbuk.ac.kr/master.php?pg_idx=147&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div table tr',
            'artMainUrl': 'https://ast.chungbuk.ac.kr/',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},

    '지구환경과학과':
        {
            'main_url': 'https://geology.chungbuk.ac.kr/master.php?pg_idx=145&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div table tr',
            'artMainUrl': 'https://geology.chungbuk.ac.kr/',
            'artUrlSubTag': 'a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},

    # 경영대학
    '경영학부':
        {
            'main_url': 'https://biz.chungbuk.ac.kr/master.php?pg_idx=7&bidx=2&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://biz.chungbuk.ac.kr/',
            'artUrlSubTag': 'div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'div:nth-child(1)',
            'art_date_tag': '#bbs_contnets > div.row > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div.row > div > h3',
            'page_date_tag': '#rows > div:nth-child(4)',
            'page_title_tag': '#rows > div > a'},

    '국제경영학과':
        {
            'main_url': 'https://ib.chungbuk.ac.kr/master.php?pg_idx=33&bidx=1&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://ib.chungbuk.ac.kr/',
            'artUrlSubTag': 'div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'div:nth-child(1)',
            'art_date_tag': '#bbs_contnets > div.row > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div.row > div > h3',
            'page_date_tag': '#rows > div:nth-child(4)',
            'page_title_tag': '#rows > div > a'},

    '경영정보학과':
        {
            'main_url': 'https://mis.chungbuk.ac.kr/master.php?pg_idx=7&bidx=3&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://mis.chungbuk.ac.kr/',
            'artUrlSubTag': 'div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'div:nth-child(1)',
            'art_date_tag': '#bbs_contnets > div.row > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div.row > div > h3',
            'page_date_tag': '#rows > div:nth-child(4)',
            'page_title_tag': '#rows > div > a'},

    # 농업생명환경대학
    '산림학과':
        {
            'main_url': 'https://forestscience.cbnu.ac.kr/index.html?pg_idx=27&bidx=4&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://forestscience.cbnu.ac.kr/',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#rows > td.no',
            'art_date_tag': '#bbs_contnets > div > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div > div > h3',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > div > a'},
    '지역건설공학과':
        {
            'main_url': 'https://jigong.chungbuk.ac.kr/index.html?pg_idx=23&bidx=2str=&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://jigong.chungbuk.ac.kr/index.html',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#rows > td.no',
            'art_date_tag': '#bbs_contnets > div > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div > div > h3',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > div > a'},

    '바이오시스템공학과':
        {
            'main_url': 'https://bse.chungbuk.ac.kr/index.html?pg_idx=48&bidx=23&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://bse.chungbuk.ac.kr/index.html',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#rows > td.no',
            'art_date_tag': '#bbs_contnets > div > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div > div > h3',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > div > a'},
    '목재종이학과':
        {
            'main_url': 'https://wood-paper.chungbuk.ac.kr/index.html?pg_idx=31&bidx=1str=&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://wood-paper.chungbuk.ac.kr/index.html',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#rows > td.no',
            'art_date_tag': '#bbs_contnets > div > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div > div > h3',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > div > a'},

    '식물자원학과':
        {
            'main_url': 'https://crop.chungbuk.ac.kr/dsoft/index.html?pg_idx=40&bidx=1&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://crop.chungbuk.ac.kr/dsoft/index.html',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#rows > td.no',
            'art_date_tag': '#bbs_contnets > div > div > div > span:nth-child(2) > b',
            'art_title_tag': 'td.title > div > a',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > div > a'},

    '환경생명화학과':
        {
            'main_url': 'https://agchem.chungbuk.ac.kr/index.html?pg_idx=35&bidx=1str=&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://agchem.chungbuk.ac.kr/index.html',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#rows > td.no',
            'art_date_tag': '#bbs_contnets > div > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div > div > h3',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > div > a'},

    '식품생명공학과':
        {
            'main_url': 'https://food.chungbuk.ac.kr/?pg_idx=240&bidx=2&id=food_s&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://food.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#rows > td.no',
            'art_date_tag': '#bbs_contnets > div > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div > div > h3',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > div > a'},

    '특용식물학과':
        {
            'main_url': 'https://tobagin.chungbuk.ac.kr/index.html?pg_idx=34&bidx=2str=&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://tobagin.chungbuk.ac.kr/index.html',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#rows > td.no',
            'art_date_tag': '#bbs_contnets > div > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div > div > h3',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > div > a'},

    '농업경제학과':
        {
            'main_url': 'https://agecon.cbnu.ac.kr/?pg_idx=119&bidx=5&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div.dambbs_list table tr',
            'artMainUrl': 'https://agecon.cbnu.ac.kr/',
            'artUrlSubTag': 'td.tdb > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head> div.date',
            'art_title_tag': '#bbs_contnets > div > div > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span'},

    '축산학과':
        {
            'main_url': 'https://animalscience.chungbuk.ac.kr/board/board.php?id=as_news&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contentsArea div table.basicList tr',
            'artMainUrl': 'https://animalscience.chungbuk.ac.kr/board/board.php',
            'artUrlSubTag': 'td.colTit > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': '#contentsArea > div > div.tableWrap > table > tbody > tr:nth-child(1) > td:nth-child(4)',
            'art_title_tag': '#contentsArea > div > dl > dd > b',
            'page_date_tag': 'td:nth-child(4)',
            'page_title_tag': 'td.colTit > a'},

    '원예과학과':
        {
            'main_url': 'https://hortisci.chungbuk.ac.kr/html/board/board.php?id=hor_news&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contentsArea div table.basicList tr',
            'artMainUrl': 'https://hortisci.chungbuk.ac.kr/html/board/board.php',
            'artUrlSubTag': 'td.colTit > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': '#contentsArea > div > div.tableWrap > table > tbody > tr:nth-child(1) > td:nth-child(4)',
            'art_title_tag': '#contentsArea > div > dl > dd > b',
            'page_date_tag': 'td:nth-child(4)',
            'page_title_tag': 'td.colTit > a'},

    # 사범대학
    '교육학과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/edu/selectBbsNttList.do?key=170&bbsNo=8&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/edu/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '국어교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/korean/selectBbsNttList.do?key=496&bbsNo=58&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '영어교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/english/selectBbsNttList.do?key=200&bbsNo=82&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '역사교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/his/selectBbsNttList.do?key=231&bbsNo=29&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/his/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},
    '지리교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/geo/selectBbsNttList.do?key=270&bbsNo=21&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/geo/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '사회교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/soc/selectBbsNttList.do?key=297&bbsNo=40&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/soc/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(6)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(6)',
            'page_title_tag': 'td.subject > a'},

    '윤리교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/ethics/selectBbsNttList.do?key=312&bbsNo=114&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '물리교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/phyedu/selectBbsNttList.do?key=350&bbsNo=66&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '화학교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/chemedu/selectBbsNttList.do?key=372&bbsNo=72&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '생물교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/bio/selectBbsNttList.do?key=399&bbsNo=2&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(6)',
            'page_title_tag': 'td.subject > a'},

    '지구과학교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/earth/selectBbsNttList.do?key=423&bbsNo=47&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '수학교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/mathedu/selectBbsNttList.do?key=763&bbsNo=88&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/mathedu/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    '체육교육과':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/physicaledu/selectBbsNttList.do?key=479&bbsNo=96&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://edu.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'td:nth-child(5)',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a'},

    # 생활과학대학
    '식품영양학과':
        {
            'main_url': 'https://foodn.chungbuk.ac.kr/main/sub.html?boardID=www27&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#awdDisplayContent div div.mdResponsiveBody div:nth-child(3) table tr',
            'artMainUrl': 'https://foodn.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.jSubject > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.jNum',
            'art_date_tag': '#AB_viewPrintArea > ul > li:nth-child(2) > div > ul',
            'art_title_tag': '#AB_viewPrintArea > ul > li:nth-child(1) > div > ul',
            'page_date_tag': 'td.jDate',
            'page_title_tag': 'td.jSubject > div > a:not(span)'},

    '아동복지학과':
        {
            'main_url': 'https://childwelfare.chungbuk.ac.kr/main/sub.html?boardID=www27&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#awdDisplayContent div div.mdResponsiveBody div:nth-child(3) table tr',
            'artMainUrl': 'https://childwelfare.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.jSubject > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.jNum',
            'art_date_tag': '#AB_viewPrintArea > ul > li:nth-child(2) > div > ul',
            'art_title_tag': '#AB_viewPrintArea > ul > li:nth-child(1) > div > ul',
            'page_date_tag': 'td.jDate',
            'page_title_tag': 'td.jSubject > div > a:not(span)'},

    '의류학과':
        {
            'main_url': 'https://fashion.chungbuk.ac.kr/main/sub.html?boardID=www42&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#awdDisplayContent div div.mdResponsiveBody div:nth-child(3) table tr',
            'artMainUrl': 'https://fashion.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.jSubject > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.jNum',
            'art_date_tag': '#AB_viewPrintArea > ul > li:nth-child(2) > div > ul',
            'art_title_tag': '#AB_viewPrintArea > ul > li:nth-child(1) > div > ul',
            'page_date_tag': 'td.jDate',
            'page_title_tag': 'td.jSubject > div > a:not(span)'},

    '주거환경학과':
        {
            'main_url': 'https://housing.chungbuk.ac.kr/main/sub.html?boardID=www27&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#awdDisplayContent div div.mdResponsiveBody div:nth-child(3) table tr',
            'artMainUrl': 'https://housing.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.jSubject > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.jNum',
            'art_date_tag': '#AB_viewPrintArea > ul > li:nth-child(2) > div > ul',
            'art_title_tag': '#AB_viewPrintArea > ul > li:nth-child(1) > div > ul',
            'page_date_tag': 'td.jDate',
            'page_title_tag': 'td.jSubject > div > a:not(span)'},

    '소비자학과':
        {
            'main_url': 'https://consumer.chungbuk.ac.kr/main/sub.html?boardID=www39&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#awdDisplayContent div div.mdResponsiveBody div:nth-child(3) table tr',
            'artMainUrl': 'https://consumer.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.jSubject > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.jNum',
            'art_date_tag': '#AB_viewPrintArea > ul > li:nth-child(2) > div > ul',
            'art_title_tag': '#AB_viewPrintArea > ul > li:nth-child(1) > div > ul',
            'page_date_tag': 'td.jDate',
            'page_title_tag': 'td.jSubject > div > a:not(span)'},

    # 수의과대학
    '수의학과':
        {
            'main_url': 'https://vetmed.cbnu.ac.kr/board/list/notice/page/',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#container div div.content_body div div.boardList table tr',
            'artMainUrl': 'https://vetmed.cbnu.ac.kr/',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.num',
            'art_date_tag': '#container > div > div.content_body > div.boardViewContainer > div.boardViewTitle > p',
            'art_title_tag': '#container > div > div.content_body > div.boardViewContainer > div.boardViewTitle > h3',
            'page_date_tag': 'td.rdate',
            'page_title_tag': 'td.title > div > a'},

    '수의예과':
        {
            'main_url': 'https://vetmed.chungbuk.ac.kr/board/list/Notification_new/page/',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#container div div.content_body div div.boardList table tr',
            'artMainUrl': 'https://vetmed.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.num',
            'art_date_tag': '#container > div > div.content_body > div.boardViewContainer > div.boardViewTitle > p',
            'art_title_tag': '#container > div > div.content_body > div.boardViewContainer > div.boardViewTitle > h3',
            'page_date_tag': 'td.rdate',
            'page_title_tag': 'td.title > div > a'},

    # 의과대학
    '의예과':
        {
            'main_url': 'https://medweb.chungbuk.ac.kr/master.php?pg_idx=110&bidx=2&id=100&cate=&pidx=0&str=&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div.dambbs_list table tr',
            'artMainUrl': 'https://medweb.chungbuk.ac.kr/master.php',
            'artUrlSubTag': 'td.tdb > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head> div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb'

        },

    '간호학과':
        {
            'main_url': 'https://nursing.chungbuk.ac.kr/?pg_idx=183&bidx=12&id=101&cate=&pidx=0&str=&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div.dambbs_list table tr',
            'artMainUrl': 'https://nursing.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.tdb > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head > div.subject',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a > span:nth-child(1)'},

    # 자율전공학부
    '자율전공학부':
        {
            'main_url': 'https://fole.chungbuk.ac.kr/board/hb1?&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#fboardlist table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title.board_title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.num',
            'art_date_tag': 'body > div.wrapper > div > div.container.sub > div.sub_con > div > div.board_view > ul.info > li.pull-right.time',
            'art_title_tag': 'body > div.wrapper > div > div.sub > div.sub_con > div > div.board_view > div.board_top_title',
            'page_date_tag': 'td.date',
            'page_title_tag': 'td.title.board_title > a.board_title_box'},

    ## 융합학과
    '조형예술학과':
        {
            'main_url': 'https://fineart.cbnu.ac.kr/bbs/bbs.php?db=notice&pgID=ID12415888101&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contentR table tr',
            'artMainUrl': 'https://fineart.cbnu.ac.kr/',
            'artUrlSubTag': 'td > nobr > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.body_num',
            'art_date_tag': '#view_bg > span',
            'art_title_tag': '#contentR table tr td nobr',
            'page_date_tag': 'td:nth-child(7)',
            'page_title_tag': '#body_line > nobr > a'},

    ## 단과대학
    '인문대학':
        {
            'main_url': 'https://humanum.chungbuk.ac.kr/www/selectBbsNttList.do?key=109&bbsNo=5&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#contents div table tr',
            'artMainUrl': 'https://humanum.chungbuk.ac.kr/www/',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.first',
            'art_date_tag': '#contents > div > div.bbs_info.clearfix > div.bbs_left.bbs_count > span:nth-child(1) > strong',
            'art_title_tag': '#contents div table tr.subject td',
            'page_date_tag': 'td.last',
            'page_title_tag': 'td.subject > a'},
    '사회과학대학':
        {
            'main_url': 'https://sscollege.chungbuk.ac.kr/board/notice?&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#fboardlist table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.text-left.text_over > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'art_date_tag': 'body > div > div.container.gitav_con_bl > div.col-xs-12.pz.post_bor_t1.post_bor_b1 > div.col-sm-2.col-xs-12.text-right.boardpt16_0.pb15.fl_center',
            'art_title_tag': 'body > div > div.container.gitav_con_bl > div.col-xs-12.pz.post_bor_t1.post_bor_b1 > div.col-sm-10.col-xs-12.fs_17.f_we5.fl_center.pt15.pb15',
            'page_date_tag': 'td:nth-child(4)',
            'page_title_tag': 'td.text-left.text_over > a'},

    '자연과학대학':
        {
            'main_url': 'https://nscience.chungbuk.ac.kr/?pg_idx=92&bidx=1&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bbs_contnets section div.dambbs_list table tr',
            'artMainUrl': 'https://nscience.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.tdb > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.tda',
            'art_date_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head.p-t-b-20 > div.col-sm-2.col-xs-12.date',
            'art_title_tag': '#bbs_contnets > div.dambbs_view > div.dambbs_head.p-t-b-20 > div.col-sm-10.col-xs-12.subject > span',
            'page_date_tag': 'td.tdc',
            'page_title_tag': 'td.tdb > a'},
    '경영대학':
        {
            'main_url': 'https://ccba.chungbuk.ac.kr/?pg_idx=8&bidx=1&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://ccba.chungbuk.ac.kr/',
            'artUrlSubTag': 'div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': '#rows > div.col-lg-1.col-md-1.col-sm-1.col-xs-3.t-a-l.p-l-r-0.font-s-12',
            'page_date_tag': '#rows > div.col-lg-1.col-md-1.col-sm-2.col-xs-4.t-a-c.p-0.font-s-12',
            'page_title_tag': 'div > a',
            'art_date_tag': '#bbs_contnets > div.rd_hd.clear.row > div.blog.v > div.font-s-12.p-b-10 > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div.rd_hd.clear.row > div.blog.v > h3',
        },
    '공과대학':
        {
            'main_url': 'https://eng.chungbuk.ac.kr/index.php?mid=eng_sub05&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bd_282_0 div.bd_lst_wrp table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.no',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a',
            'art_date_tag': '#bd_282_16879 > div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
            'art_title_tag': '#bd_282_16879 > div.rd.rd_nav_style2.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
        },
    '전자정보대학':
        {
            'main_url': 'https://ece.cbnu.ac.kr/index.php?mid=ece0602&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#bd_245_0 div.bd_lst_wrp table tr',
            'artMainUrl': '',
            'artUrlSubTag': 'td.title > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.no',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > a',
            'art_title_tag': '#bd_245_7008 > div.rd.clear > div.rd_hd.clear > div > div.top_area.ngeb > h1 > a',
            'art_date_tag': '#bd_245_7008 > div.rd.clear > div.rd_hd.clear > div > div.top_area.ngeb > div > span',
        },
    '농업생명환경대학':
        {
            'main_url': 'https://agri.chungbuk.ac.kr/index.html?pg_idx=154&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'artMainUrl': 'https://agri.chungbuk.ac.kr/index.html',
            'artUrlSubTag': 'td.title > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.no',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > div > a',
            'art_title_tag': '#bbs_contnets > div.rd_hd.clear > div > h3',
            'art_date_tag': '#bbs_contnets > div.rd_hd.clear > div > div.btm_area.ngeb.np_18px > span:nth-child(2) > b',
        },
    '사범대학':
        {
            'main_url': 'https://edu.chungbuk.ac.kr/www/selectBbsNttList.do?key=611&bbsNo=128&pageIndex=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#board div.tableA table tr',
            'artMainUrl': 'https://agri.chungbuk.ac.kr/index.html',
            'artUrlSubTag': 'td.subject > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td:nth-child(1)',
            'page_date_tag': 'td:nth-child(5)',
            'page_title_tag': 'td.subject > a',
            'art_title_tag': '#board > div > div.tit_area > ul > li:nth-child(1) > span',
            'art_date_tag': '',
        },
    '생활과학대학':
        {
            'main_url': 'https://humeco.chungbuk.ac.kr/main/sub.html?boardID=www30&page=',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#awdDisplayContent div div.mdResponsiveBody div:nth-child(3) table tr',
            'artMainUrl': 'https://humeco.chungbuk.ac.kr/',
            'artUrlSubTag': 'td.jSubject > div > a',
            'artUrlAttrName': 'href',
            'art_nid_tag': 'td.jNum',
            'page_date_tag': 'td.jDate',
            'page_title_tag': 'td.jSubject > div > a',
            'art_title_tag': '#AB_viewPrintArea > ul > li:nth-child(1) > div > ul',
            'art_date_tag': '#AB_viewPrintArea > ul > li:nth-child(2) > div > ul',
            'next_btn_tag': '#awdDisplayContent > div > div.mdDefaultW100.pagingWrap > a:nth-child(3)'
        },
}

class_dicts2 = {  # 처리못한 학과
    # 융합학과
    '약학과':  # 셀레니움, 크롤링 차단
        {
            'main_url': 'https://pharm.chungbuk.ac.kr/app/index.html?pg_idx=21',
            'target_timedelta_year': 3,
            'start_page': options.START_PAGE,
            'end_page': options.END_PAGE,
            'art_tag': '#rows',
            'art_nid_tag': 'td.no',
            'art_date_tag': '#bbs_contnets > div.rd_hd.clear > div > div > span:nth-child(2) > b',
            'art_title_tag': '#bbs_contnets > div.rd_hd.clear > div > h3',
            'page_date_tag': 'td.time',
            'page_title_tag': 'td.title > div > a',
            'next_btn_tag': '#bbs_contnets > div.bbs_serach > div.bd_pg.clear > div > a:last-child'},

}

test_dicts = {  # 안쓰면 비워놓기, 테스트리스트 있으면 위에거 안돌아감

}
