# Generated by Django 4.1 on 2023-05-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ulifeapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="meal",
            table="food",
        ),
    ]
