# Generated by Django 4.1 on 2023-05-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ulifeapp", "0003_announcement"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="announcement",
            table="notice",
        ),
    ]
