# Generated by Django 4.1 on 2024-02-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulifeapp", "0004_alter_announcement_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CBNUInfoUser",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("udid", models.CharField(blank=True, max_length=128, null=True)),
                ("fcm_token", models.CharField(blank=True, max_length=500, null=True)),
                ("renew_datetime", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "cbnuinfo_user",
            },
        ),
    ]
