# Generated by Django 4.1 on 2024-02-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulifeapp", "0006_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("host", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "keyword",
                "unique_together": {("name", "host")},
            },
        ),
    ]
