# Generated by Django 4.1 on 2024-02-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ulifeapp", "0007_keyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="FCMToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=128)),
                ("fcm_token", models.CharField(max_length=1000)),
                (
                    "keyword_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_token",
                        to="ulifeapp.keyword",
                    ),
                ),
            ],
            options={
                "db_table": "fcm_token",
            },
        ),
    ]
