# Generated by Django 4.1 on 2024-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ulifeapp", "0013_remove_keyword_unique_name_host"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="keyword",
            constraint=models.UniqueConstraint(
                fields=("name", "host"), name="unique_name_host"
            ),
        ),
    ]
