# Generated by Django 4.1 on 2024-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulifeapp', '0014_keyword_unique_name_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('keyword', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'keyword_notification',
                'managed': True,
            },
        ),
    ]
