# Generated by Django 4.1 on 2024-03-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulifeapp', '0015_keywordnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordnotification',
            name='keyword',
        ),
    ]
