# Generated by Django 4.1 on 2024-03-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulifeapp', '0016_remove_keywordnotification_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='on_alarm',
            field=models.BooleanField(default=True),
        ),
    ]
